---
apiVersion: v1
kind: Namespace
metadata:
  name: cachier-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cachier-controller-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: cachier-controller
  namespace: cachier-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    cachier.mattmoor.io/decorate: disable
  name: cachier-controller
  namespace: cachier-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cachier-controller
  template:
    metadata:
      labels:
        app: cachier-controller
    spec:
      containers:
      - args:
        - -logtostderr=true
        - -stderrthreshold=INFO
        - -resource=Deployment.v1.apps
        - -resource=ReplicaSet.v1.apps
        - -resource=StatefulSet.v1.apps
        - -resource=DaemonSet.v1.apps
        image: gcr.io/mattmoor-public/controller-c4b205fb70ed2687c5295af79a951d8a@sha256:5c14cfaeb3e2899a1647b15704104fee3910a9d448699f61ec36c789646612c6
        name: cachier-controller
      serviceAccountName: cachier-controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cachier-controller
  namespace: cachier-system
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: images.caching.internal.knative.dev
spec:
  group: caching.internal.knative.dev
  names:
    categories:
    - all
    - knative-internal
    - caching
    kind: Image
    plural: images
    shortNames:
    - img
    singular: image
  scope: Namespaced
  version: v1alpha1
