apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cachier-controller
  namespace: cachier-system
  annotations:
    cachier.mattmoor.io/decorate: disable
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cachier-controller
    spec:
      serviceAccountName: cachier-controller
      containers:
      - name: cachier-controller
        image: github.com/tamalsaha/cachier/cmd/controller
        args:
        - "-logtostderr=true"
        - "-stderrthreshold=INFO"
        # Add PodSpecable types here:
        - "-resource=Deployment.v1.apps"
        - "-resource=ReplicaSet.v1.apps"
        - "-resource=StatefulSet.v1.apps"
        - "-resource=DaemonSet.v1.apps"
